### PR TITLE
Draft of Intro Notebook

### PR DESCRIPTION
**Pull request by miraep8**
General flow:
- what is sklearn API
- what are the goals of sktime/how does this build off the sklearn principles
- simple intro to forecasting and forecasting problem.

What I am hoping to motivate in the intro:
- if you have modular components it is easy to assemble them into more complicated workstreams (eg pipelines)
- how easy tuning is - I don't say this explicitly at all. But hope to have laid the footwork for the idea that you can switch out the underlying model and/or its parameters and still interact with it the same way - which should make the introduction of the tuning interface more natural!

Would love any feedback of course!

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Nice!

General feedback:
* I think the overall structure is good
* presentation and content could be improved

Points of improvement, presentation:

* important! there needs to be more signposting. What are we doing in this notebook? What comes next? Why are we explaining sklearn first?
* less verbose, more bullet points, e.g., key features of an sklearn-like toolbox
* try to reduce "grey wall of text" in notebook. Work with newlines, highlights, headers, bullet points. Important difference between a notebook that's consumed by reading (more text is ok) vs a notebook that is presented at a conference (audience need to be able to read quickly).
* there should be a summary at the end, and further signposting


Points of improvement, content:

* there should be general intro content about `sktime`, the project, and pointers/links as in the previous pydatas
* I think it is important to spell out what key features of sklearn-like library are (in relation to the talk) - unified interface, composability, modularity, simple specification language, and map then on vignettes
* then from there leverage parallels to `sktime` and add `sktime` specifics, e.g., universal object interface
* "unified interface" vignette: it would be clearer to see that the code changes in only one location if both estimators have the same name, i.e., `clf`. Then only the imports and model definitions change!

**Comment by miraep8** [comment]
Also added a short draft of a shorter notebook to this PR. But expect that will change after the meeting today.

**Comment by miraep8** [comment]
I made some of my edits last night - however there are still a few things to still add/that I am still thinking about:
- a summary component
- potentially better signposting?
- I have moved over a lot of points into the talk rather than leaving them as text, but perhaps the balance has shifted too far in the other direction.
- I have thought about switching the first example in sktime into a regression example instead, but I worry that emphasizing the redundancy might be confusing - so instead chose to focus on a time series specific example/transition to forecasting. 
- Might add more content about sktime (the package)
- Also thinking about fleshing out/adding back in more details about exchangeability/modularity like I had in the first run through.

**Comment by fkiraly** [comment]
Let me know when you are ready. Is this ready?

Kindly rename the notebook to sth like `01_introduction.ipynb`, i.e., number at the start, lower camel case.

**Comment by miraep8** [comment]
Ready for re-review!

**Review by fkiraly — APPROVED** [review]
Perfect! :-)

what I would suggest at the end:

* credits section
* what's next section (short summary/signpost of remainder of talk)

**Comment by fkiraly** [comment]
actually, more on the wishlist:

* short section at the start, "what is sktime" with invitation; to mirror the invitation on the end. Important, as people watching the video will start here, and we want them to know that we are open and invite contributions. Can copy this from the London tutorial.
* top section numbers, 1.1, 1.2 

(I can also add that today if you are busy with the readme)

**Comment by miraep8** [comment]
Not sure what you wanted in credits, so that part is still not done (maybe you can add what you had in mind?)

**Pull request merged**
